# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: files/(issue|motd)
  - id: mixed-line-ending
    args:
      - --fix=lf
  - id: pretty-format-json
    args:
      - --autofix
  - id: requirements-txt-fixer
  - id: end-of-file-fixer
  - id: trailing-whitespace
    args:
      - --markdown-linebreak-ext=md
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.3
  hooks:
  -   id: autopep8
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.5
  hooks:
  -   id: reorder-python-imports
      language_version: python3
